apiVersion: v1beta3
kind: ReplicationController
metadata:
  labels:
    name: pxc-node1 
  name: pxc-node1 
spec:
  replicas: 1
  selector:
    name: pxc-node1 
  template:
    metadata:
      labels:
        name: pxc-node1 
    spec:
      containers:
        - command:
            - /entrypoint.sh
          resources:
            limits:
              cpu: 1
          env:
            - name: GALERA_CLUSTER
              value: "true"
            - name: WSREP_CLUSTER_ADDRESS
              value: gcomm://
            - name: WSREP_SST_USER
              value: sst
            - name: WSREP_SST_PASSWORD
              value: sst
            - name: MYSQL_USER
              value: mysql
            - name: MYSQL_PASSWORD
              value: mysql
            - name: MYSQL_ROOT_PASSWORD
              value: c-krit 
          image: "capttofu/percona_xtradb_cluster_5_6:latest"
          name: pxc-node1 
          ports:
            - containerPort: 3306 
              name: client 
            - containerPort: 4444 
              name: sst 
            - containerPort: 4567
              name: rep
            - containerPort: 4568
              name: incsst 
