apiVersion: v1
kind: Pod
metadata:
  name: pxc-node3
  labels:
    name: pxc-node3
spec:
  containers:
    - resources:
        limits: 
          cpu: 0.5
      image: capttofu/percona_xtradb_cluster_5_6:latest
      name: pxc-node1
      ports:
        - containerPort: 3306
          hostPort: 3306
          name: mysql
        - containerPort: 4444
          hostPort: 4444
#name: state-snapshot-transfer
        - containerPort: 4567
          hostPort: 4567
# name: replication-traffic
        - containerPort: 4568
          hostPort: 4568
# name: incremental-state-transfer
      env:
        - name: GALERA_CLUSTER
          value: "true"
        - name: WSREP_CLUSTER_ADDRESS
          value: gcomm://
        - name: WSREP_SST_USER
          value: sst
        - name: WSREP_SST_PASSWORD
          value: sst
        - name: MYSQL_USER
          value: mysql
        - name: MYSQL_PASSWORD
          value: mysql
        - name: MYSQL_ROOT_PASSWORD
          value: c-krit 
